### ISSUE TITLE
Port to 1.18.2

### ISSUE THREAD

**Issue by WerySkok** [nousername33/realisticcities#2]
Hello! It's a great mod, though it only supports 1.19.2 while my server works on 1.18.2. Can you add support for different Minecraft versions in the future versions of the mod? I know it will be a tough task though it will be a great investment.

**Comment by nousername33** [comment]
I'll work on it :)

**Comment by nousername33** [comment]
Gonna finish 0.2 then port it

**Comment by WerySkok** [comment]
Maybe you should also port this to Architectury but I tried it and... Well, I don't want to bother with it again...

**Comment by nousername33** [comment]
Writing this in forge is pretty much rewriting this. I will never do it xD

**Comment by nousername33** [comment]
Finished
