### ISSUE TITLE
Sign Textures Glitching

### ISSUE THREAD

**Issue by Landon-9999** [nousername33/realisticcities#4]
Seems like there is a layering issue with the signs?
![2023-04-23_20 35 53](https://user-images.githubusercontent.com/109770546/233880461-8212185b-36f3-44d8-9e9a-71311ed646d1.png)

**Comment by nousername33** [comment]
It only happens when facing north for some reason. I’ll see what I can do, 0.3 is almost done

**Comment by nousername33** [comment]
Fixed
